# Generated by Django 5.0.7 on 2024-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.TextField()),
                ('specifications', models.TextField()),
                ('historik', models.TextField()),
                ('avariem_situation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Praktic_avariem_play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avariem_situation1', models.TextField()),
                ('avariem_situation2', models.TextField()),
                ('avariem_situation4', models.TextField()),
                ('avariem_situation5', models.TextField()),
                ('avariem_situation6', models.TextField()),
                ('avariem_situation8', models.TextField()),
                ('avariem_situation7', models.TextField()),
                ('avariem_situation9', models.TextField()),
                ('avariem_situation10', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
