# Generated by Django 5.0.7 on 2024-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0002_object_praktic_avariem_play_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='files/')),
                ('my_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='object',
            old_name='date',
            new_name='text',
        ),
        migrations.AddField(
            model_name='object',
            name='date_publication',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
