# Generated by Django 5.0.7 on 2024-08-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0003_mymodel_rename_date_object_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
