# Generated by Django 5.0.7 on 2024-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0004_object_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
