# Generated by Django 5.0.7 on 2024-08-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0005_object_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='temp_field',
        ),
    ]
