# Generated by Django 5.0.7 on 2024-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0006_remove_object_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
