# Generated by Django 5.0.7 on 2024-08-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0010_object_praktic_avariem_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='praktic_avariem_play',
        ),
    ]
