# Generated by Django 5.0.7 on 2024-08-31 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0011_remove_object_praktic_avariem_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='praktic_avariem_play',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bf109.praktic_avariem_play'),
            preserve_default=False,
        ),
    ]
