# Generated by Django 5.0.7 on 2024-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0012_profile_object_praktic_avariem_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='praktic_avariem_play',
        ),
        migrations.AddField(
            model_name='object',
            name='classifikeishen',
            field=models.CharField(choices=[('model', '%s/models/%s/'), ('view', '%s/views/%s/'), ('template', '%s/templates/%s/'), ('filter', '%s/filters/#%s'), ('tag', '%s/tags/#%s')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
