# Generated by Django 5.0.7 on 2024-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0013_remove_object_praktic_avariem_play_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='classifikeishen',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
