# Generated by Django 5.0.7 on 2024-09-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0014_alter_object_classifikeishen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='avariem_situation',
        ),
        migrations.RemoveField(
            model_name='object',
            name='classifikeishen',
        ),
        migrations.RemoveField(
            model_name='object',
            name='date_publication',
        ),
        migrations.RemoveField(
            model_name='object',
            name='historik',
        ),
        migrations.RemoveField(
            model_name='object',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='object',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='object',
            name='text',
        ),
    ]
