# Generated by Django 5.0.7 on 2024-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0015_remove_object_avariem_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='avariem_situation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='classifikeishen',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='object',
            name='date_publication',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='historik',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='specifications',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
