# Generated by Django 5.0.7 on 2024-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0016_object_avariem_situation_object_classifikeishen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='classifikeishen',
        ),
    ]
