# Generated by Django 5.0.7 on 2024-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0017_remove_object_classifikeishen'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='classifikeishen',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
