# Generated by Django 5.0.7 on 2024-09-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0018_object_classifikeishen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='classifikeishen',
        ),
        migrations.AddField(
            model_name='praktic_avariem_play',
            name='aircraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_situations', to='bf109.object'),
            preserve_default=False,
        ),
    ]
