# Generated by Django 5.0.7 on 2024-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0020_promocode_sitevisitor_object_blender_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(upload_to='aircraft_photos/'),
        ),
    ]
