# Generated by Django 5.0.7 on 2024-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0021_alter_object_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
