# Generated by Django 5.0.7 on 2024-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bf109', '0022_alter_object_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='drawing',
        ),
    ]
